### ISSUE TITLE
能否增加Cloudflare Access 服务令牌支持

### ISSUE THREAD

**Issue by Silentely** [julydate/acmeDeliver#4]
我目前是通过nginx反代访问，想增加个CF 盾保护域名，因为直接访问也会返回内容（No domain specified.）耗费服务器资源，我看到可以使用Cloudflare提供的Access服务令牌作为访问依据，但是需要增加访问链接的标头项CF-Access-Client-Id: <Client ID>与 CF-Access-Client-Secret: <Client Secret>，想请教下该如何在client里增加访问时携带标头？这个可以作为选配给其他人选择性使用。
使用后直接访问效果图
![55f41036aafc71073ba5c53541e9b4db.png](https://img.mjj.today/2022/04/15/55f41036aafc71073ba5c53541e9b4db.png)
开发文档：https://developers.cloudflare.com/cloudflare-one/identity/service-auth/service-tokens/

**Comment by Raobee** [comment]
目前的client脚本使用的是curl，想要加上自定义HTTP头可以使用-H参数，请求体位于[client分支下client.sh中第43行](https://github.com/julydate/acmeDeliver/blob/23c0b0e535ba029c839399a066b372c8892c4e9d/client.sh#L43)，可以先自行修改添加-H参数使用

**Comment by Silentely** [comment]
> 目前的client脚本使用的是curl，想要加上自定义HTTP头可以使用-H参数，请求体位于[client分支下client.sh中第43行](https://github.com/julydate/acmeDeliver/blob/23c0b0e535ba029c839399a066b372c8892c4e9d/client.sh#L43)，可以先自行修改添加-H参数使用

已成功使用上了。感谢
